### ISSUE TITLE
Create a FacebookImage component

### ISSUE THREAD

**Issue by andizer** [Yoast/yoast-components#812]
The FacebookImage component will be rendered as an `img`
<img width="518" alt="yoast_-_home" src="https://user-images.githubusercontent.com/325040/51473222-10695700-1d7c-11e9-98fd-2a9b817891a0.png">
_Example of the preview with landscape image._

## Properties
* src (full path to the image)
* type (square, portrait or landscape) 

The type is relevant for the way we display the image. See the specifications below.

## Specifications
An image has a minimum width of 500px to be a landscape image. When the ratio is 1:1 it will be a square image. 
When portrait the max-height will be 236 pixels. If the width is lower than 158 px a square image is rendered.

## Styling
The image will be placed in a container:
```css
  line-height: 0;
  position: relative;
  z-index: 1;
  overflow: hidden;
  background-position: 50% 50%;
  background-repeat: no-repeat;
  display: block;
height: '{the height of the given image}px'
  width: 500px;
```

In square mode:
```css
    background-color: #fff;
    height: 158px;
    width: 158px;
```

In portrait mode:
```css
    height: 236px;
    width: 158px;
```

### Styling of the image
The image itself will have the following CSS attributes:
```css
     height: 100%;
    min-height: initial;
    width: 100%;
    position: relative;
```

In square mode:
```css
    height: auto;
```

Parent #814 814
